version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 8080:8080
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000